# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 856deee35a8ffbd81b4a2d02077a3e86e26e46003a4d8430d88c9c7ff1f3c3c8f37b577c8eaaef8a1e117d74fecb22065c6bf23ae597d3b25dc4e230a525b4e2

test:
  secret_key_base: 393d0bb73a5d5a77365d8e58e82c0494fa37d75c16a7fc165688f0fa26b6891189b8edceb7131287eee6ac59c6b44585dd269c9368edb3538ebd9243676b3ac9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
